### ISSUE TITLE
Please provide a more complete example 

### ISSUE THREAD

**Issue by tdi** [amplicity/BotMock#1]
Hi

It would be nice if you provided a complete working example of using your mock with. Can it be used with jasmine?

**Comment by amplicity** [comment]
Yes, it can be used with any testing development framework (mocha/jasmine/etc).  

All of the bot actions being tested are in `bot/indexController.js`, and can be thrown into any project using botkit. 

We're working on pushing an example app to the repo. I'll close this when that's pushed.

**Comment by amplicity** [comment]
@
